### ISSUE TITLE
Apontar cypresstest:homolog para ambiente local

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [murillowelsi/cypress-api-testing#1]
Na seguinte linha do package.json tem o script de homolog:
https://github.com/murillowelsi/cypress-api-testing/blob/055f6a69d93025eadbb6714c77511793ece527b0/package.json#L9

O que acha de alterar para `localhost`, já que o comando `cypresstest:prod` também aponta para _serverest.dev_?

```diff
- "cypresstest:homolog": "./node_modules/.bin/cypress run --spec **/*.spec.js --config baseUrl=https://serverest.dev", 
+ "cypresstest:homolog": "./node_modules/.bin/cypress run --spec **/*.spec.js --config baseUrl=http://localhost:3000", 
```

Com isso você pode subir o serverest via NPM ou Docker quando for utilizar localhost.

**Comment by murillowelsi** [comment]
Boa @PauloGoncalvesBH , obrigado pela sugestão. Já fiz o ajuste aqui.

Minha intenção com esse projeto é fazer um estudo e montar um modelo de estrutura de testes de api com o Cypress, então, sugestões são sempre bem-vindas!

Obrigado!
